slice_name: Сверка purchase и заказов
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  viz_type: pivot_table_v2
  groupbyRows:
  - mismatch_class
  groupbyColumns:
  - order_day
  metrics:
  - order_count
  adhoc_filters:
  - expressionType: SIMPLE
    subject: order_day
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
  aggregateFunction: Sum
  metricsLayout: COLUMNS
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  order_desc: true
  row_limit: 10000
  date_format: '%d.%m.%Y'
cache_timeout: null
uuid: 19600000-0000-4000-8000-000000000102
version: 1.0.0
dataset_uuid: 19600000-0000-4000-8000-000000000002
